heroku/buildpacks-go

Cargo.lock, Cargo.toml, buildpack.toml, src/main.rs
Update `libcnb` and `libherokubuildpack` to `0.10.0` and therefore to buildpack API `0.8` as well. I didn't add a CHANGELOG entry about the version bump as this isn't released yet so there is no real change for users here.
Closes GUS-W-11681878
=> Update libcnb to 0.10.0

Cargo.lock, Cargo.toml, src/cfg.rs, src/cmd.rs, src/layers/build.rs, src/layers/deps.rs, src/layers/dist.rs, src/main.rs, src/tgz.rs
https://github.com/heroku/libcnb.rs/releases/tag/v0.11.0
GUS-W-11811889.
=> Update libcnb, libcnb-test and libherokubuildpack to 0.11.0

.github/dependabot.yml
This changes the dependabot frequency to monthly to match our other buildpacks. It also adds the "skip changelog" label, which should make merging dependabot PRs slightly easier.
=> Change dependabot frequency and add labeling

.github/workflows/release.yml, CHANGELOG.md, buildpack.toml
This adds release automation via GitHub Actions. Images are published to https://hub.docker.com/r/heroku/buildpack-go, then registered at https://registry.buildpacks.io/buildpacks/heroku/go, then published to a release on this repo: https://github.com/heroku/buildpacks-go/releases/tag/heroku%2Fgo_0.1.0.
Example successful action: https://github.com/heroku/buildpacks-go/actions/runs/3594880722/jobs/6053699160
=> Add buildpack release automation

.github/workflows/inventory.yml, src/bin/diff_inventory.rs
This `inventory.yml` action is similar to what we have for the Node.js Classic and Cloud Native Buildpacks. Here's how it works:
1. runs on a regular schedule (weeknights)
2. Attempts to generate a human readable list of go versions that are tagged in the github.com/golang/go repo, but not included in inventory.toml with `diff_inventory.rs` (this output is used for changelog and commit messages).
3. Adds the above output to the changelog.
4. Updates the inventory.toml with the missing versions. Again, by checking for versions tagged in github.com/golang/go repo, then also looking up the sha from Golang's binary host.
5. Opens a PR against this repo with the changes, using the diff message from before.
Example PR that this automation generated: #75
=> Add inventory automation

CHANGELOG.md, buildpack.toml
Updates the buildpack version and the changelog for 0.1.3, which includes new go versions.
=> Prepare 0.1.3 release

CHANGELOG.md, buildpack.toml
This prepares 0.1.4 for release, which will include:
- go1.19.9
- go1.20.4
=> Prepare 0.1.4 for release

.github/workflows/release.yml
The release automation is failing due to IP whitelisting: https://github.com/heroku/buildpacks-go/actions/runs/4929777921/jobs/8809844516#step:16:19.
This PR changes the release workflow to use an IP whitelisted runner.
=> Use IP address whitelisted runner for releasing buildpacks

CHANGELOG.md, Cargo.lock, Cargo.toml, buildpack.toml, src/main.rs, src/proc.rs
Updates CNB Buildpack API to 0.9 and libcnb.rs to 0.12. This required some changes to `Process`, which are explained upstream: https://github.com/heroku/libcnb.rs/releases/tag/v0.12.0.
=> Update to CNB Buildpack API 0.9 and libcnb.rs to 0.12

CHANGELOG.md, buildpack.toml
This sets up release 0.1.5, which includes new Go versions and an update to buildpack API 0.9.
=> Prepare release 0.1.5

.github/workflows/prepare-release.yml, .github/workflows/release.yml, CHANGELOG.md, buildpack.toml
This sets up the release automation scripts from [languages-github-actions](https://github.com/heroku/languages-github-actions) for the Go buildpack.
Also in this PR:
* adds the target Docker repository to `buildpack.toml` to align with the metadata used by other Heroku buildpacks
[W-13658753](https://gus.lightning.force.com/a07EE00001UktfwYAB)
=> Use the shared release automation for Go buildpacks

src/vrs.rs
Clippy is complaining across all CI runs. This is a new lint that comes with Rust 1.72.
Fixes #150
=> Drop useless vec and fix clippy error

.github/workflows/inventory.yml
This brings in some of the latest improvements from the Node.js CNB inventory automation. Namely: Uses the linguist GitHub App, supports multiline diff messages, and sets the inventory update PR to auto-merge.
This is needed since our inventory automation is no longer able to create PRs. Recent automation exits with this message: `Error: GitHub Actions is not permitted to create or approve pull requests.`. [Example](https://github.com/heroku/buildpacks-go/actions/runs/6227212544/job/16901352387).
=> Update inventory automation with github app and auto merge

tests/integration_test.rs
Since the `heroku/buildpacks:20` image is about to be deprecated, and has been replaced by the newly added `heroku/builder:20` for those that need to use a Heroku-20 based builder.
The build and run images used by `heroku/builder:20` are the same as those used by `heroku/buildpacks:20` - the only differences between the builders are the included buildpacks (which is somewhat irrelevant for these integration tests, since the buildpack under test will be injected instead).
The smoke tests in the `heroku/builder` GitHub repo are still testing against all image variants (until such time as we make the legacy images error with an EOL message), so we still have test coverage against them.
See:
https://github.com/heroku/builder/pull/394
https://salesforce.quip.com/0JtbAYiWZYk6
GUS-W-14186015.
=> Switch tests from `heroku/buildpacks:20` to `heroku/builder:20`

README.md
Since the repository has been renamed:
https://github.com/heroku/cnb-builder-images/issues/396
GUS-W-14201543.
=> Update builder repo name to cnb-builder-images

CHANGELOG.md
The changelog intro says it conforms to the https://keepachangelog.com style, but previously the content actually did not. Now it does match that style, making it consistent with our other CNBs.
See:
https://keepachangelog.com/en/1.1.0/
I've also added links to the GitHub PRs for each entry. Whilst adding these is extra work for each PR, I feel it's worthwhile for end-users -- I very much find it useful when projects we use do the same.
GUS-W-14283439.
=> Make the changelog conform to the keepachangelog.com style

.github/workflows/inventory.yml
For the same reasons as:
https://github.com/heroku/languages-github-actions/pull/109
GUS-W-14283772.
=> Don't add the `automation` label to inventory PRs

CHANGELOG.md, buildpack.toml
Adds the buildpack `description` to `buildpack.toml` with a style matching that discussed in:
https://github.com/heroku/cnb-builder-images/issues/408
The `description` field is displayed on the CNB registry's page for the buildpack.
In addition, I've cleaned up the `[metadata]` table/subtables to match the more concise style used by the Procfile and Python CNBs.
GUS-W-14121598.
=> Add buildpack description to buildpack.toml

Cargo.toml, src/bin/diff_inventory.rs, src/bin/update_inventory.rs, src/lib.rs, src/main.rs, tests/integration_test.rs
As of the Cargo included in Rust 1.74, lints can now be configured in `Cargo.toml` across whole crates/workspaces:
https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html
https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section
This reduces the boilerplate, and the chance that we forget to enable lints in some targets.
Since this feature requires Rust 1.74, the MSRV has also been bumped (however, libcnb 0.16.0 already requires Rust 1.74, so in practice this is a no-op).
GUS-W-14523792.
=> Switch to Cargo.toml based lint configuration

Cargo.toml, clippy.toml, src/cfg.rs, src/inv.rs, src/layers/build.rs, src/layers/dist.rs, src/main.rs, src/tgz.rs
Enables some off-by-default lints that we already use in the `libcnb.rs` repository.
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unreachable-pub
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unsafe-code
https://rust-lang.github.io/rust-clippy/master/index.html#/panic_in_result_fn
https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_used
GUS-W-14523792.
=> Enable additional rustc and Clippy lints

Cargo.toml, buildpacks/go/Cargo.toml, common/go-utils/Cargo.toml
As of Cargo 1.75 the `version` property in `Cargo.toml` is now optional, and if omitted is the same as having specified `version = "0.0.0"` and `publish = false`:
https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-175-2023-12-28
https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field
Therefore for crates that we do not publish, we can now remove both the `version` and `publish` properties, avoiding the need for the fake `0.0.0` version that differs from the actual buildpack version in `buildpack.toml`.
In addition, the `Cargo.toml` `description` property has been removed, since:
- it's unused unless the crate is published
- it duplicates the description in `buildpack.toml` / the README etc
GUS-W-14821120.
=> Simplify Cargo metadata for `publish = false` crates

Cargo.lock, Cargo.toml, buildpacks/go/Cargo.toml, buildpacks/go/src/main.rs, buildpacks/go/tests/integration_test.rs, common/go-utils/src/bin/diff_inventory.rs, common/go-utils/src/bin/update_inventory.rs
For parity with our other CNBs.
This lint wasn't enabled previously, due to many false positives from the binary utils having previously been part of the main crate - however, they've since been split out into the `go-utils` crate in this repo.
Enabling this lint found some unused/mis-categorised deps, which have now been fixed.
=> Enable `unused_crate_dependencies` lint

CONTRIBUTING.md, README.md
This adds a modified version of the [`CONTRIBUTING.md` guide from the Salesforce OSS template](https://github.com/salesforce/oss-template/blob/main/CONTRIBUTING.md). It's fairly similar to the guide added here: https://github.com/heroku/buildpacks/pull/1.
=> Add CONTRIBUTING.md guide

README.md
This PR updates the README.md according to the guideline set forth [here](https://salesforce.quip.com/f38GA9uAqpCk).
To see the new README.md without the diff: [Readable](https://github.com/heroku/buildpacks-go/blob/update-readme/README.md).
=> Update README.md to Heroku Cloud Native Buildpacks guideline

Cargo.lock, buildpacks/go/CHANGELOG.md, buildpacks/go/Cargo.toml, buildpacks/go/buildpack.toml, buildpacks/go/src/layers/build.rs, buildpacks/go/src/layers/deps.rs, buildpacks/go/src/layers/dist.rs, buildpacks/go/src/layers/target.rs
This updates libcnb from 0.17.0 to 0.19.0, and implements buildpack API 0.10.0 in the process:
- Bumps the Buildpack API version to 0.10, and now sets os/arch to linux/amd64 in `buildpack.toml`'s `[[targets]]`  section (in favor of the now deprecated `[[stacks]]`.
- Closes https://github.com/heroku/buildpacks-go/pull/221.
=> Implement buildpack API 0.10

buildpacks/go/inventory.toml, buildpacks/go/src/layers/dist.rs, common/go-utils/src/inv.rs
This PR builds on the work completed in https://github.com/heroku/buildpacks-go/pull/216, and focuses on:
* Decoupling the Go specific "architecture" format from the platform information stored in the inventory. It does so by:
* Removing the combined `Artifact#architecture` field (e.g. `linux-amd64`) in favor of two new fields, `os` and `arch`, with values that we explicitly define (rather than relying on Go's terminology).
* In particular, that now means the `arch` field is set to `x86_64` rather than the Go idiomatic/specific `amd64` naming.
* Similarly, when adding support for more archs and OSs, we'll like prefer values like `aarch64` and `macos` (e.g. values that map to Rust's [arch](https://doc.rust-lang.org/std/env/consts/constant.ARCH.html) and …
=> Refactor artifact architecture and url

buildpacks/go/CHANGELOG.md, buildpacks/go/inventory.toml, common/go-utils/src/bin/diff_inventory.rs, common/go-utils/src/bin/update_inventory.rs, common/go-utils/src/inv.rs
This PR builds on https://github.com/heroku/buildpacks-go/pull/229, and updates the inventory utils to support artifacts for multiple architectures and operating systems.
* `Artifact` now implements the `Hash` trait.
* `Artifact#hash` is implemented to rely solely on the [`sha_checksum` value](https://github.com/heroku/buildpacks-go/pull/230/files#diff-093f94a1f107af2f526a22b23862bc48ded092574cb775569a20214d221f9b01R30). I think it's likely safe to assume the checksum values will be unique for each Artifact entry, but please share any concerns regarding that approach.
* This should be considered carefully as this will of course be used extensively throughout both the inventory utils, and the buildpack itself, for [cache invalidation, metadata …
=> Add inventory support for arm64 linux artifacts

buildpacks/go/src/layers/build.rs, buildpacks/go/src/layers/dist.rs, buildpacks/go/src/main.rs, buildpacks/go/tests/integration_test.rs
Prefer using the full `Artifact` instead of just the `Artifact#go_version`, in buildpack layers. This changes the buildpack output to include more information about the Go artifact (i.e. architecture and os, and where the artifact is downloaded from) - and allow us to add more target architectures (e.g. https://github.com/heroku/buildpacks-go/pull/233) that factor in the target os/arch in addition to the version
=> Prefer artifact over version in buildpack layers

buildpacks/go/inventory.toml, common/go-utils/src/inv.rs
As the title suggests, this PR simply renames the `go_version` field to just `version`, to further streamline the `Artifact` and `inventory.toml` format.
=> Rename Artifact go_version to version

buildpacks/go/CHANGELOG.md, buildpacks/go/buildpack.toml
This PR adds the linux/arm64 target in `buildpack.toml`.
For testing the buildpack, an arm64 compatible builder can be created locally (using the newly released `heroku-24` base images (tested on an m1 Mac with Docker's `containerd` feature enabled), and a basic builder configuration file) - e.g. something like this:
`builder-24/builder.toml`:
```toml
description = "Heroku-24 (Ubuntu 24.04) builder sans buildpacks"
[stack]
id = "heroku-24"
build-image = "heroku/heroku:24-build.nightly"
run-image = "heroku/heroku:24.nightly"
[lifecycle]
version = "0.19.0"
```
Create the builder:
pack builder create heroku/builder:24 --config ./builder-24/builder.toml
Compile and package the CNBs:
cargo libcnb package
cargo libcnb package --target aarch64-unknown-linux-musl
To test that the `x86_64` version …
=> Support arm64

buildpacks/go/buildpack.toml
Our publish automation is broken as can be seen [here](https://github.com/heroku/buildpacks-go/actions/runs/8574984168). The issue is described in https://github.com/buildpacks/pack/issues/2047, but basically `pack buildpack package` will error without a `[[stacks]]` key. This has been fixed in https://github.com/buildpacks/pack/pull/2081, but it has not yet been released. 
This change reintroduces `stacks` into `buildpack.toml` so that `pack buildpack package` will work on this buildpack again. This is the same fix we applied in https://github.com/heroku/buildpacks-procfile/pull/210.
=> Reintroduce stacks into buildpack.toml for compatibility with pack

common/inventory-utils/src/inv.rs
This isn't currently used by this buildpack, but will be used by other buildpacks using the shared inventory logic.
`darwin` is the [OCI compliant name (`GOOS`) for macOS](https://go.dev/doc/install/source#environment) and (for convenience) `Os::Darwin` can be parsed from either `darwin` (as used by for instance the nodejs.org releases feed) and `osx` (as used in the .NET release feed).
=> Add Darwin to Os enum

buildpacks/go/inventory.toml, buildpacks/go/src/tgz.rs, buildpacks/go/tests/integration_test.rs, common/go-utils/src/inv.rs, common/inventory-utils/src/inv.rs
Fixes https://github.com/heroku/buildpacks-go/issues/243
=> Use OCI compliant arch ids

common/go-utils/src/vrs.rs, common/inventory-utils/Cargo.toml, common/inventory-utils/src/inv.rs, common/inventory-utils/src/semvrs.rs
This allows use of for instance `semver::Version` and `semver::VersionReq` out of the box for users of the shared library code.
=> Remove Version marker trait

buildpacks/go/CHANGELOG.md
There's really nothing to do here except add a changelog entry; the `buildpack.toml` already has both targets. The next release will be published as multi-arch, since https://github.com/heroku/languages-github-actions/pull/194 is merged.
=> `arm64` and multi-arch support

Cargo.lock, Cargo.toml, buildpacks/go/Cargo.toml
#259 only updated `libherokubuildpack`, missing `libcnb*` dependencies for some reason, even after recreation. This PR updates them all manually.
=> Update to libcnb 0.21.0

.github/workflows/ci.yml, buildpacks/go/tests/integration_test.rs
This PR adds integration tests for heroku-24 (arm64 and amd64). 
It also changes the integration tests to a matrix so that each supported builder + arch is it's own job. Previously, the integration tests tested all builders in one job, but that's a less optimal strategy now that there are 3 builders and 2 architectures to support.
One of the tests had hard-coded `amd64` expectations, that has also been made generic.
=> heroku-24 and multi-arch integration testing

buildpacks/go/CHANGELOG.md, buildpacks/go/src/layers/build.rs, buildpacks/go/src/main.rs, common/go-utils/src/vrs.rs
The build cache (which includes intermediate compilation artifacts) should be invalidated when the target arch, distro, or distro version changes. These assets are unlikely to be valid after a major change to the OS, especially if any C bindings are involved. We were already supporting expiration based on architecture changes, but not distro details.
Conversely, the build cache artifacts may be valid after a minor go version change (patch level change in semver parlance). We were previously expiring these assets on any go version change, which meant frequent, perhaps unnecessary invalidation.  
This PR introduces build cache invalidation based on distro changes, and prevents build cache invalidation for minor go version changes.
=> Improve build cache expiration logic

.github/workflows/ci.yml
Smaller runners are more plentiful, and we no longer need to install Docker, either!
=> Use pub-hk-ubuntu-22.04-arm-small

.github/workflows/ci.yml
libc-dev and Rust are already on the base image
Follow-up to #268
=> Drop unnecessary installs for arm64 from workflow

.github/workflows/inventory.yml
The use-app-token action is deprecated: https://github.com/heroku/use-app-token-action/pull/17
GUS-W-16159740
=> Use actions/create-github-app-token instead of heroku/use-app-token

.github/workflows/check_changelog.yml, .github/workflows/ci.yml, .github/workflows/inventory.yml
Similar to the Node.js CNB repo, this repo is occasionally hitting Docker Hub rate limit errors on the ARM jobs in the matrix like so:
https://github.com/heroku/buildpacks-go/actions/runs/9796334219/job/27051359595#step:8:10
These are due to the fact that the `pub-hk-ubuntu-22.04-arm-small` ARM runner also has a static IP enabled, which means all traffic from any runners in that group go through a single load balancer with the fixed IP. This not only causes throughput/reliability issues, but means that we're more likely to hit the Docker Hub rate limit.
As such, we requested the creation of some new runner groups that separate out the "need a fixed IP for writes" vs "need more compute or an ARM CPU" use-cases. As an added bonus these groups are also using Ubuntu 24.04. See: …
=> Fix issues with Docker Hub rate limits in CI

Cargo.toml, buildpacks/go/tests/integration_test.rs
Fixes CI issues like these: https://github.com/heroku/buildpacks-go/actions/runs/10137876783/job/28028716108.
Also fixes a few `needless_borrows_for_generic_args` issues in the integration test.
=> Set pedantic priority

buildpacks/go/CHANGELOG.md, buildpacks/go/src/main.rs, buildpacks/go/tests/fixtures/procfile_http_123/Procfile, buildpacks/go/tests/fixtures/procfile_http_123/go.mod, buildpacks/go/tests/fixtures/procfile_http_123/main.go, buildpacks/go/tests/integration_test.rs
Customers are often surprised and sometimes annoyed when this buildpack adds processes not in the `Procfile`. This prevents adding processes when a `Procfile` is present. 
In the future, I'd like to change this conditional to be dependent on `heroku/procfile` contributing, rather than the specific `Procfile` file.
Related: #85
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001z1TA7YAM/view)
=> Don't set processes when Procfile is present

buildpacks/go/src/layers/dist.rs, buildpacks/go/src/main.rs
I took a similar approach to Manuel's here: https://github.com/heroku/buildpacks-jvm/pull/721. This covers one layer (`go_dist`). Other layers will come in later PRs. I dropped the cache version expiration - these haven't been used.
=> Migrate `go_dist` to struct layer API.

buildpacks/go/src/cmd.rs, buildpacks/go/src/layers/deps.rs, buildpacks/go/src/main.rs
Similarly to https://github.com/heroku/buildpacks-go/pull/338, this converts the `go_deps` layer to the struct layer API. It's very similar to Manuel's approach in https://github.com/heroku/buildpacks-jvm/pull/721. 
Additionally, the `layer_version` functionality has never been used, so I've removed it.
And finally, with the resolution of https://github.com/heroku/libcnb.rs/issues/475, libcnb is able to delete this layer correctly, so the `go_clean` step is no longer required and has been removed.
=> Migrate `go_deps` to struct layer API

buildpacks/go/src/layers/target.rs, buildpacks/go/src/main.rs
Similarly to https://github.com/heroku/buildpacks-go/pull/338, this converts the `go_target` layer to the struct layer API. It's very similar to Manuel's approach in https://github.com/heroku/buildpacks-jvm/pull/721.
=> Migrate `go_target` to struct layer API

buildpacks/go/src/layers/build.rs, buildpacks/go/src/main.rs
Similarly to https://github.com/heroku/buildpacks-go/pull/338, this converts the `go_build` layer to the struct layer API. It's very similar to Manuel's approach in https://github.com/heroku/buildpacks-jvm/pull/721. 
Additionally, the `layer_version` functionality has never been used, so I've removed it.
=> Migrate `go_build` layer to struct API

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/inventory.yml
The full-version Git tags used by Actions are mutable (as seen in recent events in the wider GitHub Actions community), so pinning third-party Actions to a SHA is recommended:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
The version tag has been added after the pin as a comment (as a readability aid) in a format that Dependabot will keep up to date: https://github.com/dependabot/dependabot-core/issues/4691
I've also enabled Dependabot grouping for GitHub Actions updates to reduce PR noise.
GUS-W-18051077.
=> Pin SHA of third-party GitHub Actions

Cargo.lock, Cargo.toml, buildpacks/go/Cargo.toml, buildpacks/go/src/tgz.rs
This brings in the latest libcnb, complete with `tracing` pipeline support. With this new support, we can now `#[instrument]` functions with spans and errors that will be available for the export pipeline. Downloading the go distribution is one of the first areas I'd like to instrument. `instrument` functionality generally wants `std::fmt::Debug` for arguments and any errors, so there was a change to function signatures.
=> Update to libcnb.rs 0.28; instrument go_download

Cargo.lock
Supersedes #357, which didn't pick up `libcnb` and `libcnb-test` updates for some reason. Bringing in the latest to get the tracing bugfix: https://github.com/heroku/libcnb.rs/pull/926.
=> Update libcnb and friends

.github/workflows/ci.yml, Cargo.toml, buildpacks/go/src/main.rs
This is mostly a copy of https://github.com/heroku/buildpacks-jvm/pull/766. 
This sets up a GitHub actions job that uploads an HTML report of unit test code coverage to the run summary.
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000027eTguYAE/view)
=> Add coverage reporting via cargo-llvm-cov

buildpacks/go/CHANGELOG.md
The changelog entry for #368 was linking to a PR in the PHP CNB repo instead.
=> Fix PR URL in CHANGELOG
